### ISSUE TITLE
datasheet says only need to wait 6ms for a reading

### ISSUE THREAD

**Issue by pwr33** [sleemanj/HMC5883L_Simple#2]
Hi, thanks for library, cool, had to do a new #define for my mounting orientation which worked nicely based on your tricksy abstraction.

datasheet says only need to wait 6ms for a reading, I was wondering which was right?

on a single read you wait 66ms which is (actually nearer 67ms) the time between readings in default continuous mode, but perhaps the/each single reading only takes 6ms to do..... ???

**Comment by sleemanj** [comment]
I don't remember why it would be 66, at a guess maybe I determined it experimentally, or possibly a mistake and I meant to write 6.

**Comment by pwr33** [comment]
I monitored drdy in standard continuous rate and it goes low and back high in the same millisecond and remains high for 67 or 68ms, little bit of output from test

drdy 0, 15053
drdy 1, 15053
drdy 0, 15121
drdy 1, 15121
drdy 0, 15188
drdy 1, 15188
